fix #79 Goal Sabotage is broken
Eredrim/pvparena pull request #89
Opened 2021-03-06 10:03 UTC by Oruss7

2021-03-11 20:47 UTC, Eredrim requested changes

2021-03-11 20:47 UTC, Eredrim commented on src/net/slipcor/pvparena/core/Language.java
> +        GOAL_SABOTAGE_YOUCANNOTSELFDESTROY("nulang.goal.sabotage.youcannotselfdestroy", "You can not ignite your own TNT!"),
I suggest to simplify with `GOAL_SABOTAGE_NOSELFDESTROY` and `nulang.goal.sabotage.noselfdestroy`

2021-03-11 20:47 UTC, Eredrim commented on lang/lang_es-es.yml
> +      notgooditem: 'You need sabotage tool to ignite the TNT.'
You don't need to add english sentences to other languages. If language key is not found, default value (in english) from Language.java will be used.

2021-03-12 20:38 UTC, Eredrim commented on src/net/slipcor/pvparena/goals/GoalSabotage.java
> +                world.playSound(location, Sound.ENTITY_GENERIC_EXPLODE, 20, 2);
Really cool, this fake explosion!

2021-03-12 20:39 UTC, Eredrim approved these changes

2021-03-12 20:39 UTC, merged

2021-03-13 07:27 UTC, Oruss7 commented on src/net/slipcor/pvparena/goals/GoalSabotage.java
> +                world.playSound(location, Sound.ENTITY_GENERIC_EXPLODE, 20, 2);
It's when region is protected, the tnt disapear and nothing... so I added it =)